### ISSUE TITLE
POST /dives does not return event field

### ISSUE THREAD

**Issue by VebMazer** [Sukeltaja-App/sukeltaja-backend#15]
POST /dives does not return event field

This is not really a problem unless in the future there is a need for listing dives independently from events, and links to dives are wanted and if it turns out this field is not returned in GET requests either.(Have not tested this yet.)

**Comment by VebMazer** [comment]
Right now it does not cause any problems since it is easily fixed in front-end.

**Comment by wametsol** [comment]
Should be fixed now.
The event id was provided to Dive at /POST request, but there was a typo and it tried to get id of the event, which was already just a id of the event. Removed the id from event.id at /POST request, and works now.
Closing the issue now.
