### ISSUE TITLE
User should not be able to have multiple roles in an event

### ISSUE THREAD

**Issue by luupanu** [Sukeltaja-App/sukeltaja-backend#33]
Currently there are no checks to avoid a user having multiple roles (creator, admin, participant) in an event. A user should only have one role, since otherwise it creates some problems in the frontend. 

JavaScript does not have an easy solution to filter out duplicates due to how the language interprets object equality. A Set() would be used normally `[ ...new Set(array) ]`, but this does not work with objects. This leads to [some not so readable code](https://github.com/Sukeltaja-App/sukeltaja-frontend/blob/e6a42e575d678b4e3d171f64ea631439daf1f0b8/src/components/OngoingEventScreens/OngoingEvent.js#L114-L124) in the frontend where distinct users should be displayed.

**Comment by VebMazer** [comment]
This problem has been solved now that accepting an admin invite deletes the user accepting it from the participants list, if it exists there.
